swagger: "2.0"
info:
  title: TODO App
  description: This is API for TODO App Documentation
  version: 1.0
  contact:
    email: tommy3713@gmail.com
  liscence:
    name: Apache 2.0
    url: "http://www.apache.org/liscences/LIS"
  servers:
    -url: https://localhost:8000
    description: This is my local Server
schemes: http


#Return Todos From get request
paths:
  /api/todos:
    get:
      tags:
          - todos
      summary: return array of todos.
      description: 
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: array
            items: object
            properties:
              id:
                type: string
              taskName:
                type: string
              status:
                type: string
            example: [{id: "1", taskName: "Do homework", status: "todo"}]
    post:
      tags:
        - todos
      summary: post new task
      description:
      parameters:
        - name: body
          in: body
          schema:
                $ref: "#/definitions/item"
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: array
            items: object
            properties:
              id:
                type: string
              taskName:
                type: string
              status:
                type: string
            example: [{id: "1", taskName: "Do homework", status: "todo"}]
  /api/todos/{id}:
    parameters:
      - type: string
        format: int64
        name: id
        in: path
        required: true
    delete:
      tags:
        - todos
      summary: delete one task
      description: 
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: array
            items: object
            properties:
              id:
                type: string
              taskName:
                type: string
              status:
                type: string
            example: [{id: "1", taskName: "Do homework", status: "todo"}]
    put:
      tags:
        - todos
      summary: get certain task
      description: 
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: array
            items: object
            properties:
              id:
                type: string
              taskName:
                type: string
              status:
                type: string
            example: [{id: "1", taskName: "Do homework", status: "todo"}]
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: string
      taskName:
        type: string
      status:
        type: string